from decentralizedlearning.algs.sac import SACHyperPar
def get_hyperpar(name):
    if name=="default_masac": #Config for tag and navigation
        return SACHyperPar(hidden_dims_actor=(128, 128),
                           hidden_dims_critic=(256, 256),
                           hidden_dims_model=(200, 200, 200, 200),
                           gamma=0.95,
                           tau=0.01,
                           lr_actor=0.003,
                           lr_critic=0.003,
                           lr_model=0.01,
                           l2_norm=0.001,
                           step_random=0,
                           update_every_n_steps=1,
                           update_model_every_n_steps=250,
                           n_steps=1,
                           delay=1,
                           n_models=10,
                           batch_size=256,
                           weight_decay=0.0,
                           alpha=0.1,
                           use_model=False,
                           use_model_stochastic=True,
                           diverse=True,
                           autotune=True,
                           target_entropy=-2.0,
                           name=name,
                           use_common_actor=False,
                           use_common_critic=False,
                           real_ratio=0.1)

    if name=="default_mambpo": #Config for tag and navigation
        return SACHyperPar(hidden_dims_actor=(128, 128),
                           hidden_dims_critic=(256, 256),
                           hidden_dims_model=(200, 200, 200, 200),
                           gamma=0.95,
                           tau=0.01,
                           lr_actor=0.003,
                           lr_critic=0.003,
                           lr_model=0.01,
                           l2_norm=0.001,
                           step_random=0,
                           update_every_n_steps=1,
                           update_model_every_n_steps=250,
                           n_steps=10,
                           delay=1,
                           n_models=10,
                           batch_size=256,
                           weight_decay=0.0,
                           alpha=0.1,
                           use_model=True,
                           use_model_stochastic=True,
                           diverse=True,
                           autotune=True,
                           target_entropy=-2.0,
                           name=name,
                           use_common_actor=False,
                           use_common_critic=False,
                           real_ratio=0.1)

    if name=="cheetah": #Config for cheetah
        return SACHyperPar(hidden_dims_actor=(256, 256),
                           hidden_dims_critic=(256, 256),
                           hidden_dims_model=(200, 200, 200, 200),
                           gamma=0.99,
                           tau=0.005,
                           lr_actor=0.0003,
                           lr_critic=0.0003,
                           lr_model=0.001,
                           l2_norm=0.00000,
                           step_random=5000,
                           update_every_n_steps=1,
                           update_model_every_n_steps=250,
                           n_steps=40,
                           n_models=10,
                           batch_size=256,
                           weight_decay=0.0,
                           alpha=0.05,
                           use_model=True,
                           use_model_stochastic=True,
                           diverse=True,
                           autotune=True,
                           target_entropy=-3.0,
                           name=name)
    else:
        raise Exception("Config not found")